# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parley < Formula
  desc "Terminal API client: collections, environments, auth, scripting, WebSocket testing"
  homepage "https://github.com/dhitalkamal/parley"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhitalkamal/parley/releases/download/v0.2.0/parley_darwin_amd64.tar.gz"
      sha256 "352b2e0397e87ce93a7de023dd7176f7084017497bf1bd4404dfaf5f41503a94"

      define_method(:install) do
        bin.install "parley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhitalkamal/parley/releases/download/v0.2.0/parley_darwin_arm64.tar.gz"
      sha256 "bc42cac7715cbe35947b634913dac6f4b5e29f54af4ba5132f89b56f300783cb"

      define_method(:install) do
        bin.install "parley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhitalkamal/parley/releases/download/v0.2.0/parley_linux_amd64.tar.gz"
      sha256 "f3073bfabda1d59eadda535ffa6d467dd0aa2db0ea246b12f82435c1b576d278"
      define_method(:install) do
        bin.install "parley"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhitalkamal/parley/releases/download/v0.2.0/parley_linux_arm64.tar.gz"
      sha256 "4c727b79f722e8e74c1661de389329007fec2923b01f31358e1496f1f5567889"
      define_method(:install) do
        bin.install "parley"
      end
    end
  end

  test do
    assert_predicate bin/"parley", :executable?
  end
end
